#!/bin/bash
set -e

function exist_command() {
  local c=$1
  if ! type -p ${c} >/dev/null; then
    return 1
  fi
  return 0
}

function check() {
  local required_command=(fzf ghq)
  for c in ${required_command[@]}; do
    if ! exist_command "${c}"; then
      echo "${c} not found on the system" >&2
      exit 1
    fi
  done
}

function choose() {
  local target="${1}"
  local cc="cat"
  if exist_command "bat"; then
    cc="bat"
  fi
  local args
  if [ -z ${target} ]; then
    ghq list | fzf --reverse --preview "${cc} {1}/README.md" | xargs printf "%s/%s" $(ghq root)
  else
    ghq list --full-path | fzf --reverse -f ${target} -1 -0 -e | head -n 1
  fi
}

check
selected="$(choose ${1})"
[ -n "${selected}" ] || exit 1
\cd ${selected}
$SHELL
